---
- name: Stop Tomcat
  command: "{{ tomcat_path }}/bin/shutdown.sh"

- name: Copy war file
  copy:
    src: "/var/lib/jenkins/workspace/{{ JOB_NAME }}/webapp/target/webapp.war"
    dest: "{{ tomcat_path }}/webapps/webapps.war"

- name: Start Tomcat
  command: "{{ tomcat_path }}/bin/startup.sh"
