---
- name: Put Site in Maintenance
  include: putMaintenanceMode.yml
  tags:
  - PutMaintenance

- name: Deploy War
  include: deployWarFile.yml
  tags:
  - DeployWar 

- name: Revoke Maintenance mode
  include: revokeMaintenanceMode.yml
  tags:
  - RevokeMaintenance
